# Generated by Django 4.2.13 on 2024-05-23 12:17

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="grade_info",
            fields=[
                (
                    "id",
                    models.CharField(
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                        verbose_name="学号",
                    ),
                ),
                ("sname", models.CharField(max_length=32, verbose_name="姓名")),
                ("lid", models.CharField(max_length=10, verbose_name="课程编号")),
                ("lname", models.CharField(max_length=64, verbose_name="课程名称")),
                ("grade", models.SmallIntegerField(null=True, verbose_name="成绩")),
                (
                    "is_retaking",
                    models.BooleanField(default=False, verbose_name="是否正在重修"),
                ),
            ],
            options={
                "verbose_name": "成绩信息",
                "db_table": "grade_info",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="les_info",
            fields=[
                (
                    "id",
                    models.CharField(
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                        verbose_name="课程编号",
                    ),
                ),
                ("lname", models.CharField(max_length=64, verbose_name="课程名称")),
                ("teacher", models.CharField(max_length=64, verbose_name="教师")),
                ("credit", models.SmallIntegerField(verbose_name="学分")),
                ("hour", models.SmallIntegerField(verbose_name="学时")),
                ("mname", models.CharField(max_length=64, verbose_name="专业")),
                ("dname", models.CharField(max_length=64, verbose_name="学院")),
            ],
            options={
                "verbose_name": "课程信息",
                "db_table": "lesson_info",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="stu_info",
            fields=[
                (
                    "id",
                    models.CharField(
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                        verbose_name="学号",
                    ),
                ),
                ("password", models.CharField(max_length=16, verbose_name="密码")),
                (
                    "img",
                    models.CharField(
                        max_length=32, null=True, unique=True, verbose_name="照片"
                    ),
                ),
                ("name", models.CharField(max_length=32, verbose_name="姓名")),
                ("gender", models.BooleanField(default=True, verbose_name="性别")),
                (
                    "prize",
                    models.CharField(max_length=256, null=True, verbose_name="奖项"),
                ),
                (
                    "punishment",
                    models.CharField(max_length=256, null=True, verbose_name="惩罚"),
                ),
                ("status", models.SmallIntegerField(default=0, verbose_name="学业状态")),
                (
                    "retake_chances",
                    models.SmallIntegerField(default=2, verbose_name="重修机会"),
                ),
                ("birthday", models.DateField(verbose_name="生日")),
                ("data_in", models.DateField(verbose_name="入学时间")),
                ("major", models.CharField(max_length=64, verbose_name="专业")),
                ("department", models.CharField(max_length=64, verbose_name="学院")),
                ("avg_gpa", models.FloatField(null=True, verbose_name="绩点")),
            ],
            options={
                "verbose_name": "学生信息",
                "db_table": "stu_info",
                "managed": False,
            },
        ),
    ]
