# Generated by Django 4.2.13 on 2024-05-24 01:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_department_major_stu_lesson_sl"),
    ]

    operations = [
        migrations.CreateModel(
            name="sl_info",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sid", models.CharField(max_length=10, verbose_name="学号")),
                ("sname", models.CharField(max_length=32, verbose_name="姓名")),
                ("lid", models.CharField(max_length=10, verbose_name="课程编号")),
                ("lname", models.CharField(max_length=64, verbose_name="课程名称")),
                ("teacher", models.CharField(max_length=64, verbose_name="教师")),
                ("credit", models.SmallIntegerField(verbose_name="学分")),
                ("hour", models.SmallIntegerField(verbose_name="学时")),
                (
                    "is_retaking",
                    models.BooleanField(default=False, verbose_name="是否正在重修"),
                ),
                ("grade", models.SmallIntegerField(null=True, verbose_name="成绩")),
            ],
            options={
                "verbose_name": "选课信息",
                "db_table": "sl_info",
                "managed": False,
            },
        ),
        migrations.AlterModelTable(
            name="les_info",
            table="les_info",
        ),
    ]
